version: '3.7'




volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16


services:

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.1.0
    ports: 
      - 9113:9113
    networks:
      back-tier:
        ipv4_address: 172.18.0.3
    restart: always 
    command: 
      - '--nginx.scrape-uri=http://CHANGEME:8080/stub_status'
