# my global config
global:
  scrape_interval:     1s 
  evaluation_interval: 1s 
  scrape_timeout: 1s
  external_labels:
      monitor: 'my-project'

scrape_configs:
  
  - job_name: 'nginx'
    static_configs:
      - targets: ['172.18.0.3:9113']
    metrics_path: "/metrics"
    scrape_interval: 1s

